controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

# JWT Token
auth:
  path: /api/auth
  methods: ["POST"]

api_refresh_token:
  path: /api/token/refresh
